# Configurations
title:            王阳的免费API
longtitle:        王阳的免费API 永久免费 实用API 
author:           王阳
email:            youngwang1228@gmail.com
description: >
  王阳的免费API 永久免费 实用API 节假日API 手机号码属地查询 IP属地查询 OCR 语音识别 语音转文字 二维码生成

version:          1.0
gitbook_version:  3.2.3

url:              'https://youngwang1228.github.io'
baseurl:          ''
rss:              RSS

# bootstrap: use the remote theme for the site itself
remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min: 1
  h_max: 2

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     assets/logo/logo.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Permalinks
#permalink:                /:categories/:year-:month-:day-:title:output_ext
permalink:                /:categories/:title:output_ext

# Disqus comments
# disqushandler:            sighingnow

exclude:
  - _drafts

# collections:
#   pages:
#     output: true
#     permalink: /:collection/:path/

page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
